name: Update QLD Stock Data
on:
  schedule:
    # Run daily at 5 AM UTC
    - cron: '0 3 * * *'
  # push:
  #   branches:
  #     - main
      
jobs:
  update-qld-stock-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you want to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the script to update QLD stock data
      env:
        TOKEN: ${{ secrets.TOKEN }}  # Use the secret here
      run: |
        python main.py