name: Update QLD Stock Data

on:
  schedule:
    # Run daily at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-qld-stock-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Verify TOKEN
      run: |
        if [ -z "${TOKEN}" ]; then
          echo "TOKEN is not set."
          exit 1
        else
          echo "TOKEN is set."
        fi
      env:
        TOKEN: ${{ secrets.TOKEN }}
    - name: Run the script to update QLD stock data
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        python main.py
